"""create example_widgets

Revision ID: create_example_widgets
Revises: fastkit_outbox_inbox
Create Date: 2026-07-27
"""

from __future__ import annotations

from alembic import op

revision = "create_example_widgets"
down_revision = "fastkit_outbox_inbox"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    CREATE TABLE example_widgets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        payload JSONB NOT NULL DEFAULT '{}'::jsonb,
        status VARCHAR(16) NOT NULL DEFAULT 'pending',
        attempts INTEGER NOT NULL DEFAULT 0
            CHECK (attempts >= 0),
        last_error TEXT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
    """)
    op.execute(
        "CREATE INDEX idx_example_widgets_status_pending ON example_widgets (status) "
        "WHERE status IN ('pending', 'running')"
    )
    op.execute(
        "COMMENT ON TABLE example_widgets IS "
        "'示范业务域-示例表, 供业务方参考(命名故意叫 widget 避免被误读为系统任务)'"
    )
    op.execute("COMMENT ON COLUMN example_widgets.id IS '主键, 自增'")
    op.execute(
        "COMMENT ON COLUMN example_widgets.payload IS "
        "'业务数据 JSONB, 示范专用字段 fail_until_attempt 控制注入失败'"
    )
    op.execute(
        "COMMENT ON COLUMN example_widgets.status IS "
        "'状态, 可选值: pending, running, finished, failed'"
    )
    op.execute(
        "COMMENT ON COLUMN example_widgets.attempts IS "
        "'consumer 端已消费次数, 与 envelope.attempts 同步 +1'"
    )
    op.execute(
        "COMMENT ON COLUMN example_widgets.last_error IS "
        "'最近一次异常摘要, 前 500 字符'"
    )
    op.execute("COMMENT ON COLUMN example_widgets.created_at IS '创建时间'")
    op.execute("COMMENT ON COLUMN example_widgets.updated_at IS '更新时间'")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS example_widgets")
