"""fastkit framework schema v1: fastkit_outbox + fastkit_inbox + pg_notify trigger

Revision ID: fastkit_outbox_inbox
Revises:
"""

from alembic import op

revision = "fastkit_outbox_inbox"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE fastkit_outbox (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            aggregate TEXT NOT NULL,
            routing_key TEXT NOT NULL,
            payload JSONB NOT NULL,
            headers JSONB NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            published_at TIMESTAMPTZ,
            attempts INT NOT NULL DEFAULT 0 CHECK (attempts >= 0),
            last_error TEXT,
            next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            status VARCHAR(16) NOT NULL DEFAULT 'pending',
            dead_reason TEXT
        )
        """
    )

    op.execute(
        "COMMENT ON TABLE fastkit_outbox IS "
        "'同事务发件箱: 业务事务内原子落表, relay 异步投递到 RabbitMQ, 保证至少一次投递'"
    )
    op.execute("COMMENT ON COLUMN fastkit_outbox.id IS '自增主键'")
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.aggregate IS '聚合根标识 (业务实体类型 + ID)'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.routing_key IS "
        "'事件路由键 (对应 events.py 中注册的 routing_key)'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.payload IS "
        "'消息体 (JSONB, 遵守 events.py 中注册的 Pydantic schema)'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.headers IS '消息头 (envelope 元数据, 默认空对象)'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.created_at IS '落表时间 (与业务事务同 commit)'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.published_at IS "
        "'成功投递到 broker 的时间; NULL 表示尚未发布'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.attempts IS '已重试次数 (从 0 开始计数)'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.last_error IS '最近一次投递失败的原因'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.next_attempt_at IS "
        "'下次重试时间; relay 按此字段扫描待发行'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.status IS "
        "'行状态: pending=待发/重试中, published=已成功投递到 broker, dead=已达 max_attempts 进入死信'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_outbox.dead_reason IS "
        "'进入死信的原因 (一般最后一次失败的错误摘要)'"
    )

    op.execute(
        "CREATE INDEX idx_fastkit_outbox_pending ON fastkit_outbox (next_attempt_at, id) "
        "WHERE status = 'pending'"
    )
    op.execute(
        "CREATE INDEX idx_fastkit_outbox_published ON fastkit_outbox (published_at) "
        "WHERE published_at IS NOT NULL"
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION fastkit_notify_outbox() RETURNS TRIGGER AS $$
        BEGIN
            PERFORM pg_notify('fastkit_outbox_new', NEW.id::text);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER fastkit_outbox_notify AFTER INSERT ON fastkit_outbox "
        "FOR EACH ROW EXECUTE FUNCTION fastkit_notify_outbox()"
    )

    op.execute(
        """
        CREATE TABLE fastkit_inbox (
            consumer TEXT NOT NULL,
            message_id TEXT NOT NULL,
            processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (consumer, message_id)
        )
        """
    )

    op.execute(
        "COMMENT ON TABLE fastkit_inbox IS "
        "'消费侧幂等去重表: (consumer, message_id) 联合唯一, 防止消息重复消费'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_inbox.consumer IS "
        "'消费者标识 (service + handler 维度)'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_inbox.message_id IS "
        "'消息 ID (来自 envelope, 用于幂等去重)'"
    )
    op.execute(
        "COMMENT ON COLUMN fastkit_inbox.processed_at IS '消费侧处理完成时间'"
    )
    op.execute(
        "CREATE INDEX idx_fastkit_inbox_processed_at ON fastkit_inbox (processed_at)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS idx_fastkit_inbox_processed_at")
    op.execute("DROP TABLE IF EXISTS fastkit_inbox")
    op.execute("DROP TRIGGER IF EXISTS fastkit_outbox_notify ON fastkit_outbox")
    op.execute("DROP FUNCTION IF EXISTS fastkit_notify_outbox()")
    op.execute("DROP INDEX IF EXISTS idx_fastkit_outbox_published")
    op.execute("DROP INDEX IF EXISTS idx_fastkit_outbox_pending")
    op.execute("DROP TABLE IF EXISTS fastkit_outbox")
